In [13]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/raw/train.csv')

C:\Users\bert_\AppData\Local\Temp\ipykernel_35088\4229903785.py:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/train.csv')

In [14]:
df.head()

,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,FTM,FTA,FT_per,twoPM,twoPA,twoP_per,TPM,TPA,TP_per,blk_per,stl_per,ftr,yr,ht,num,porpag,adjoe,pfr,year,type,Rec_Rank,ast_tov,rimmade,rimmade_rimmiss,midmade,midmade_midmiss,rim_ratio,mid_ratio,dunksmade,dunksmiss_dunksmade,dunks_ratio,pick,drtg,adrtg,dporpag,stops,bpm,obpm,dbpm,gbpm,mp,ogbpm,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,player_id,drafted
0,South Alabama,SB,26,29.5,97.3,16.6,42.5,44.43,1.6,4.6,15.8,16.3,10,14,0.714,26,68,0.382,13,39,0.333,0.3,1.5,13.1,So,2-Jun,NaN,0.258086,89.3938,2.5,2009,all,NaN,1.823646,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.321,108.527,0.893017,49.9644,-4.995140,-1.623360,-3.371780,-4.723150,14.5769,-2.781990,-1.941150,0.1923,0.6154,0.8077,1.1923,0.3462,0.0385,3.8846,b2716b2d-3422-4959-9fe7-fe496414a4e8,0.0
1,Utah St.,WAC,34,60.9,108.3,14.9,52.4,54.48,3.8,6.3,13.6,19.8,30,45,0.667,56,113,0.496,20,51,0.392,1.0,1.1,27.4,So,4-Jun,NaN,1.334920,100.0660,3.4,2009,all,NaN,1.631621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.078,104.017,1.880030,111.9290,0.593024,1.385490,-0.792469,-0.300196,24.5294,-0.052263,-0.247934,0.6765,1.2647,1.9412,1.8235,0.4118,0.2353,5.9412,bb387960-e3a0-4ffd-96ae-184bad07cb8a,0.0
2,South Florida,BE,27,72.0,96.2,21.8,45.7,47.98,2.1,8.0,14.7,15.9,45,67,0.672,67,157,0.427,50,154,0.325,0.0,0.9,21.5,Sr,4-Jun,NaN,2.274070,104.1070,1.7,2009,all,NaN,1.081662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.556,102.154,2.763870,115.0210,0.003161,1.024770,-1.021610,0.665065,33.1852,1.548230,-0.883163,0.6296,2.3333,2.9630,1.9630,0.4815,0.0000,12.1852,89bbdf11-eadd-4de4-95e5-03f7e2874aa1,0.0
3,Pepperdine,WCC,30,44.5,97.7,16.0,53.6,53.69,4.1,9.4,13.7,23.8,14,27,0.519,25,63,0.397,28,62,0.452,0.8,1.9,21.6,Sr,4-Jun,NaN,0.552857,93.2086,2.0,2009,all,NaN,0.942830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108.858,106.556,1.218710,84.1698,-0.977798,-0.502574,-0.475224,-0.736233,17.9667,-0.342775,-0.393459,0.7000,1.4333,2.1333,1.1000,0.5667,0.1333,4.9333,0c87ada8-8446-4ea2-a05b-bd07aed5f37a,0.0
4,Pacific,BW,33,56.2,96.5,22.0,52.8,54.31,8.3,18.6,8.2,22.7,64,114,0.561,93,176,0.528,0,0,0.000,1.9,1.3,64.8,Sr,8-Jun,NaN,1.060130,97.8554,3.8,2009,all,NaN,0.491229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.052,100.724,1.992790,128.0280,-1.836060,-1.946040,0.109983,-2.353180,22.9091,-1.684860,-0.668318,1.4242,3.3030,4.7273,0.8485,0.4545,0.3333,7.5758,84661e00-ad20-4308-817e-efa8da52a86c,0.0

In [ ]:
pd.options.display.max_columns=300
pd.options.display.max_rows=300

In [4]:
df.shape

(46618, 64)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46618 entries, 0 to 46617
Data columns (total 64 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   team                 46618 non-null  object
 1   conf                 46618 non-null  object
 2   GP                   46618 non-null  int64
 3   Min_per              46618 non-null  float64
 4   Ortg                 46618 non-null  float64
 5   usg                  46618 non-null  float64
 6   eFG                  46618 non-null  float64
 7   TS_per               46618 non-null  float64
 8   ORB_per              46618 non-null  float64
 9   DRB_per              46618 non-null  float64
 10  AST_per              46618 non-null  float64
 11  TO_per               46618 non-null  float64
 12  FTM                  46618 non-null  int64
 13  FTA                  46618 non-null  int64
 14  FT_per               46618 non-null  float64
 15  twoPM                46618 non-null  int64
 16  twoPA                46618 non-null  int64
 17  twoP_per             46618 non-null  float64
 18  TPM                  46618 non-null  int64
 19  TPA                  46618 non-null  int64
 20  TP_per               46618 non-null  float64
 21  blk_per              46618 non-null  float64
 22  stl_per              46618 non-null  float64
 23  ftr                  46618 non-null  float64
 24  yr                   46326 non-null  object
 25  ht                   46554 non-null  object
 26  num                  41939 non-null  object
 27  porpag               46618 non-null  float64
 28  adjoe                46618 non-null  float64
 29  pfr                  46618 non-null  float64
 30  year                 46618 non-null  int64
 31  type                 46618 non-null  object
 32  Rec_Rank             14337 non-null  float64
 33  ast_tov              43151 non-null  float64
 34  rimmade              40860 non-null  float64
 35  rimmade_rimmiss      40860 non-null  float64
 36  midmade              40860 non-null  float64
 37  midmade_midmiss      40860 non-null  float64
 38  rim_ratio            38119 non-null  float64
 39  mid_ratio            38050 non-null  float64
 40  dunksmade            40860 non-null  float64
 41  dunksmiss_dunksmade  40860 non-null  float64
 42  dunks_ratio          20400 non-null  float64
 43  pick                 1207 non-null   float64
 44  drtg                 46576 non-null  float64
 45  adrtg                46576 non-null  float64
 46  dporpag              46576 non-null  float64
 47  stops                46576 non-null  float64
 48  bpm                  46576 non-null  float64
 49  obpm                 46576 non-null  float64
 50  dbpm                 46576 non-null  float64
 51  gbpm                 46576 non-null  float64
 52  mp                   46582 non-null  float64
 53  ogbpm                46576 non-null  float64
 54  dgbpm                46576 non-null  float64
 55  oreb                 46582 non-null  float64
 56  dreb                 46582 non-null  float64
 57  treb                 46582 non-null  float64
 58  ast                  46582 non-null  float64
 59  stl                  46582 non-null  float64
 60  blk                  46582 non-null  float64
 61  pts                  46582 non-null  float64
 62  player_id            46618 non-null  object
 63  drafted              46618 non-null  float64
dtypes: float64(49), int64(8), object(7)
memory usage: 22.8+ MB

In [15]:
df.describe(include='all')

,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,FTM,FTA,FT_per,twoPM,twoPA,twoP_per,TPM,TPA,TP_per,blk_per,stl_per,ftr,yr,ht,num,porpag,adjoe,pfr,year,type,Rec_Rank,ast_tov,rimmade,rimmade_rimmiss,midmade,midmade_midmiss,rim_ratio,mid_ratio,dunksmade,dunksmiss_dunksmade,dunks_ratio,pick,drtg,adrtg,dporpag,stops,bpm,obpm,dbpm,gbpm,mp,ogbpm,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,player_id,drafted
count,46618,46618,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46618.000000,46326,46554,41939.0,46618.000000,46618.000000,46618.000000,46618.000000,46618,14337.000000,43151.000000,40860.000000,40860.000000,40860.000000,40860.000000,38119.000000,38050.000000,40860.000000,40860.000000,20400.000000,1207.000000,46576.000000,46576.000000,46576.000000,46576.000000,46576.000000,46576.000000,46576.000000,46576.000000,46582.000000,46576.000000,46576.000000,46582.000000,46582.000000,46582.000000,46582.000000,46582.000000,46582.000000,46582.000000,46618,46618.000000
unique,355,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,38,80.0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20377,NaN
top,Army,A10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jr,7-Jun,1.0,NaN,NaN,NaN,NaN,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2336a719-c648-440c-821d-32fb0d9760bf,NaN
freq,176,1880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12401,4615,1743.0,NaN,NaN,NaN,NaN,46618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,NaN
mean,NaN,NaN,23.542988,37.339013,91.784360,18.164578,44.424392,47.571397,5.654071,12.575102,10.923008,20.535915,33.357909,47.887597,0.579193,41.521408,85.960444,0.424809,15.379274,44.595264,0.224779,1.877063,1.731048,38.111972,NaN,NaN,NaN,0.779567,89.277666,4.278710,2013.528036,NaN,53.217744,0.922210,27.779809,46.572614,14.853377,41.602619,0.562907,0.322901,3.774498,4.230470,0.866099,33.235294,103.364709,103.513641,1.427313,82.521563,-2.518313,-1.900248,-0.618064,-2.552051,16.949385,-2.088273,-0.463778,0.778630,1.867124,2.645755,1.066943,0.527743,0.283606,5.732429,NaN,0.009524
std,NaN,NaN,10.076829,28.019801,30.235568,6.181982,18.026404,17.217909,9.985025,11.041089,9.430012,12.210669,37.306108,50.190318,0.266445,43.820264,85.556152,0.191180,21.482081,57.557171,0.191479,6.271323,2.148502,36.821462,NaN,NaN,NaN,1.340548,30.669615,4.819912,2.873213,NaN,27.821187,0.691221,29.893780,47.108673,17.834037,45.221695,0.191550,0.170364,7.884873,8.631777,0.229589,16.624054,10.569908,11.405002,1.057080,65.092602,7.701851,5.186198,4.415293,8.305566,10.633054,6.160620,3.303826,0.745045,1.464894,2.096319,1.170469,0.469654,0.422755,4.942544,NaN,0.097127
min,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,-6.792410,-39.021300,0.000000,2009.000000,NaN,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,-1330.060000,-1292.020000,-0.857238,0.043033,-88.479400,-92.593500,-57.459400,-242.523000,0.000000,-141.539000,-100.984000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000
25%,NaN,NaN,17.000000,9.600000,83.900000,14.600000,40.000000,43.770000,1.900000,8.400000,4.600000,14.900000,4.000000,7.000000,0.500000,5.000000,13.000000,0.371000,0.000000,1.000000,0.000000,0.000000,0.900000,20.000000,NaN,NaN,NaN,-0.173758,79.145350,2.800000,2011.000000,NaN,30.200000,0.448264,4.000000,8.000000,2.000000,6.000000,0.500000,0.250000,0.000000,0.000000,0.827600,20.000000,99.093975,98.128300,0.521836,19.951825,-5.406862,-4.020425,-2.280647,-5.419053,7.266700,-4.463895,-1.747553,0.228600,0.681800,1.000000,0.217400,0.157900,0.000000,1.538500,NaN,0.000000
50%,NaN,NaN,28.000000,35.900000,97.000000,18.100000,47.500000,50.720000,4.500000,11.800000,9.100000,19.300000,20.000000,32.000000,0.657000,27.000000,60.000000,0.457000,4.000000,17.000000,0.273000,0.800000,1.500000,33.300000,NaN,NaN,NaN,0.389350,94.498250,3.800000,2014.000000,NaN,55.200000,0.807717,18.000000,32.000000,8.000000,26.000000,0.579700,0.333300,0.000000,0.000000,1.000000,34.000000,103.752000,103.864000,1.253835,75.980950,-1.829445,-1.357925,-0.577818,-1.807265,16.642900,-1.581525,-0.335180,0.550000,1.600000,2.235300,0.666700,0.419400,0.131600,4.428600,NaN,0.000000
75%,NaN,NaN,31.000000,62.200000,106.800000,21.800000,53.000000,55.947500,8.200000,15.900000,15.200000,24.700000,51.000000,74.000000,0.750000,65.000000,136.000000,0.522000,24.000000,73.000000,0.357000,2.500000,2.200000,48.700000,NaN,NaN,NaN,1.490375,106.508750,5.200000,2016.000000,NaN,77.400000,1.250035,42.000000,72.000000,22.000000,62.000000,0.666700,0.400000,4.000000,4.000000,1.000000,48.000000,108.316250,109.385000,2.152052,134.325500,1.403800,1.019898,1.127100,1.395935,26.312500,1.018088,1.048375,1.129000,2.724100,3.806500,1.529000,0.793100,0.366700,9.033050,NaN,0.000000
max,NaN,NaN,41.000000,98.000000,834.000000,50.000000,150.000000,150.000000,1576.600000,1385.000000,100.000000,100.000000,312.000000,374.000000,1.000000,311.000000,615.000000,1.000000,147.000000,394.000000,1.000000,1072.000000,128.300000,1000.000000,NaN,NaN,NaN,8.658190,678.942000,720.000000,2018.000000,NaN,100.000000,12.001200,238.000000,358.000000,222.000000,532.000000,1.000000,1.000000,122.000000,132.000000,1.000000,60.000000,131.461000,144.685000,5.800530,360.572000,685.313000,161.995000,523.319000,269.508000,50.000000,225.485000,78.985500,5.933300,11.545500,14.533300,10.000000,4.000000,5.258100,29.968800,NaN,1.000000

In [16]:
df.isna().any()

team                   False
conf                   False
GP                     False
Min_per                False
Ortg                   False
usg                    False
eFG                    False
TS_per                 False
ORB_per                False
DRB_per                False
AST_per                False
TO_per                 False
FTM                    False
FTA                    False
FT_per                 False
twoPM                  False
twoPA                  False
twoP_per               False
TPM                    False
TPA                    False
TP_per                 False
blk_per                False
stl_per                False
ftr                    False
yr                      True
ht                      True
num                     True
porpag                 False
adjoe                  False
pfr                    False
year                   False
type                   False
Rec_Rank                True
ast_tov                 True
rimmade                 True
rimmade_rimmiss         True
midmade                 True
midmade_midmiss         True
rim_ratio               True
mid_ratio               True
dunksmade               True
dunksmiss_dunksmade     True
dunks_ratio             True
pick                    True
drtg                    True
adrtg                   True
dporpag                 True
stops                   True
bpm                     True
obpm                    True
dbpm                    True
gbpm                    True
mp                      True
ogbpm                   True
dgbpm                   True
oreb                    True
dreb                    True
treb                    True
ast                     True
stl                     True
blk                     True
pts                     True
player_id              False
drafted                False
dtype: bool

In [8]:
cat_cols = df.select_dtypes(include=['object','category']).columns.to_list()
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.to_list()

In [9]:
cat_cols

['team', 'conf', 'yr', 'ht', 'num', 'type', 'player_id']

In [11]:
num_cols

['GP',
 'Min_per',
 'Ortg',
 'usg',
 'eFG',
 'TS_per',
 'ORB_per',
 'DRB_per',
 'AST_per',
 'TO_per',
 'FTM',
 'FTA',
 'FT_per',
 'twoPM',
 'twoPA',
 'twoP_per',
 'TPM',
 'TPA',
 'TP_per',
 'blk_per',
 'stl_per',
 'ftr',
 'porpag',
 'adjoe',
 'pfr',
 'year',
 'Rec_Rank',
 'ast_tov',
 'rimmade',
 'rimmade_rimmiss',
 'midmade',
 'midmade_midmiss',
 'rim_ratio',
 'mid_ratio',
 'dunksmade',
 'dunksmiss_dunksmade',
 'dunks_ratio',
 'pick',
 'drtg',
 'adrtg',
 'dporpag',
 'stops',
 'bpm',
 'obpm',
 'dbpm',
 'gbpm',
 'mp',
 'ogbpm',
 'dgbpm',
 'oreb',
 'dreb',
 'treb',
 'ast',
 'stl',
 'blk',
 'pts',
 'drafted']

In [ ]:
df_clean = df.copy()

In [7]:
df_cleaned = df_clean.copy()